[package]
name = "native-app"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"]}
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
tracing-web = {workspace = true }
web-sys = { workspace = true, features = [
    "Document",
    "Window",
    "Element",
]}
